# Generated by Django 4.2.5 on 2023-09-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='name_id',
            field=models.PositiveIntegerField(help_text='Enter 1 for default name id', unique=True),
        ),
        migrations.AlterField(
            model_name='agents',
            name='password',
            field=models.CharField(help_text='Enter 1 for default password', max_length=200),
        ),
    ]
