# Generated by Django 4.2.1 on 2023-09-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polling_units', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lga',
            old_name='state',
            new_name='state_id',
        ),
    ]
