# Generated by Django 4.2.1 on 2023-09-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_units', '0002_rename_state_lga_state_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='user_ip_address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
