# Generated by Django 4.2.1 on 2023-09-15 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling_units', '0003_ward_user_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='lga_id',
            field=models.ForeignKey(help_text="If you can't find the LGA, then add it, using the green plus button", on_delete=django.db.models.deletion.CASCADE, to='polling_units.lga'),
        ),
    ]
