# Generated by Django 4.2.1 on 2023-09-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_units', '0005_alter_pollingunit_polling_unit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingunit',
            name='polling_unit_id',
            field=models.PositiveIntegerField(),
        ),
    ]
